column_order = {
    "sampleMetadata": ["samp_name","samp_category","neg_cont_type","pos_cont_type","materialSampleID","sample_derived_from","sample_composed_of","rel_cont_id","biological_rep_relation","decimalLongitude","decimalLatitude","verbatimLongitude","verbatimLatitude","verbatimCoordinateSystem","verbatimSRS","geo_loc_name","eventDate","eventDurationValue","verbatimEventDate","verbatimEventTime","env_broad_scale","env_local_scale","env_medium","habitat_natural_artificial_0_1","samp_collect_method","samp_collect_device","samp_size","samp_size_unit","samp_store_temp","samp_store_sol","samp_store_dur","samp_store_loc","dna_store_loc","samp_store_method_additional","samp_mat_process","filter_passive_active_0_1","stationed_sample_dur","pump_flow_rate","pump_flow_rate_unit","prefilter_material","size_frac_low","size_frac","filter_diameter","filter_surface_area","filter_material","filter_name","precip_chem_prep","precip_force_prep","precip_time_prep","precip_temp_prep","prepped_samp_store_temp","prepped_samp_store_sol","prepped_samp_store_dur","prep_method_additional","date_ext","samp_vol_we_dna_ext","samp_vol_we_dna_ext_unit","nucl_acid_ext_lysis","nucl_acid_ext_sep","nucl_acid_ext","nucl_acid_ext_kit","nucl_acid_ext_modify","dna_cleanup_0_1","dna_cleanup_method","concentration","concentration_unit","concentration_method","ratioOfAbsorbance260_280","pool_dna_num","nucl_acid_ext_method_additional","assay_name","detected_notDetected","samp_weather","minimumDepthInMeters","maximumDepthInMeters","tot_depth_water_col","elev","alt","temp","chlorophyll","light_intensity","ph","ph_meth","salinity","suspend_part_matter","tidal_stage","turbidity","water_current","humidity","solar_irradiance","wind_direction","wind_speed","host_species","host_life_stage","host_tot_mass","host_tot_mass_unit","host_height","host_height_unit","host_length","host_length_unit","diss_inorg_carb","diss_inorg_carb_unit","diss_inorg_nitro","diss_inorg_nitro_unit","diss_org_carb","diss_org_carb_unit","diss_org_nitro","diss_org_nitro_unit","diss_oxygen","diss_oxygen_unit","tot_diss_nitro","tot_diss_nitro_unit","tot_inorg_nitro","tot_inorg_nitro_unit","tot_nitro","tot_nitro_unit","tot_part_carb","tot_part_carb_unit","tot_org_carb","tot_org_carb_unit","tot_org_c_meth","tot_nitro_content","tot_nitro_content_unit","tot_nitro_cont_meth","tot_carb","tot_carb_unit","part_org_carb","part_org_carb_unit","part_org_nitro","part_org_nitro_unit","nitrate","nitrate_unit","nitrite","nitrite_unit","nitro","nitro_unit","org_carb","org_carb_unit","org_matter","org_matter_unit","org_nitro","org_nitro_unit"],

    "ampData": ["samp_name","technical_rep_id","assay_name","pcr_plate_id","quantificationCycle","rfu","estimatedNumberOfCopies_method","estimatedNumberOfCopies","estimatedNumberOfCopies_unit","estimatedNumberOfCopies_error","estimatedNumberOfCopies_error_type"],

    "stdData": ["samp_name","technical_rep_id","assay_name","pcr_plate_id","std_conc","std_conc_unit","quantificationCycle","rfu","efficiency","r2","slope","intercept"],

    "eLowQuantData": ["assay_name","num_detect","estimatedNumberOfCopies","estimatedNumberOfCopies_unit","estimatedNumberOfCopies_error","estimatedNumberOfCopies_error_type"],

    "experimentRunMetadata": ["samp_name","assay_name","pcr_plate_id","lib_id","seq_run_id","lib_conc","lib_conc_unit","lib_conc_meth","phix_perc","mid_forward","mid_reverse","filename","filename2","checksum_filename","checksum_filename2","associatedSequences","input_read_count","output_read_count","output_otu_num","otu_num_tax_assigned"],

    "taxaRaw": ["seq_id","dna_sequence","kingdom","phylum","class","order","family","genus","specificEpithet","scientificName","scientificNameAuthorship","taxonRank","taxonID","taxonID_db","verbatimIdentification","accession_id","accession_id_ref_db","percent_match","percent_query_cover","confidence_score","identificationRemarks"],

    "taxaFinal": ["seq_id","dna_sequence","kingdom","phylum","class","order","family","genus","specificEpithet","scientificName","scientificNameAuthorship","taxonRank","taxonID","taxonID_db","verbatimIdentification","accession_id","accession_id_ref_db","percent_match","percent_query_cover","confidence_score","identificationRemarks"]
}