import os
import yaml
from collections import OrderedDict

# Path to the directory containing individual slot YAML files
SLOTS_DIR = "slots"
OUTPUT_SCHEMA = "schema.yaml"
GLOSSARY_FILENAME = "glossary_annotation.yaml"

# Base schema structure
schema = OrderedDict({
    "id": "https://w3id.org/fairie/schema",
    "name": "faire_checklist",
    "description": "A LinkML schema representing the FAIRe checklist, rebuilt from individual slots.",
    "version": "1.0.3",
    "prefixes": {
        "linkml": "https://w3id.org/linkml/",
        "schema": "https://schema.org/",
        "dwc": "http://rs.tdwg.org/dwc/terms/",
        "mixs": "https://w3id.org/mixs/",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "default_prefix": "faire",
    "imports": ["linkml:types"]
})

# Load glossary (if exists) and insert first
glossary_path = os.path.join(SLOTS_DIR, GLOSSARY_FILENAME)
if os.path.exists(glossary_path):
    with open(glossary_path, "r") as g:
        glossary_block = yaml.safe_load(g)
        schema["annotations"] = glossary_block.get("annotations", {})

# Initialize empty containers
schema["slots"] = OrderedDict()
schema["enums"] = OrderedDict()
schema["classes"] = {
    "MetadataChecklist": {
        "description": "A metadata record based on the FAIRe checklist.",
        "slots": []
    }
}


def normalize_slot_def(slot_def: dict) -> None:
    """
    BW: Normalize slot definitions so they conform to LinkML expectations:
    - Convert skos:exactMatch into slot_uri + exact_mappings
    - Move term_type into annotations to avoid unknown top-level keys
    """
    if not isinstance(slot_def, dict):
        return

    # Handle skos:exactMatch -> slot_uri + exact_mappings
    if "skos:exactMatch" in slot_def:
        raw_matches = slot_def.pop("skos:exactMatch") or []

        # Normalise to a list of strings
        if not isinstance(raw_matches, list):
            raw_matches = [raw_matches]

        iris = []
        for m in raw_matches:
            # Allow pipe-separated IRIs in a single string
            parts = str(m).split("|")
            for p in parts:
                p = p.strip()
                if p:
                    iris.append(p)

        if iris:
            # If no slot_uri is set, use the first IRI
            if "slot_uri" not in slot_def:
                slot_def["slot_uri"] = iris[0]

            existing_exact = slot_def.get("exact_mappings", [])
            if not isinstance(existing_exact, list):
                existing_exact = [existing_exact]

            for iri in iris:
                if iri not in existing_exact:
                    existing_exact.append(iri)

            slot_def["exact_mappings"] = existing_exact

    # Move term_type into annotations
    if "term_type" in slot_def:
        term_type = slot_def.pop("term_type")
        annotations = slot_def.get("annotations") or {}
        # Don't overwrite an existing annotation if one is already present
        annotations.setdefault("term_type", term_type)
        slot_def["annotations"] = annotations


# Process all non-glossary YAML files alphabetically
slot_files = sorted(
    f for f in os.listdir(SLOTS_DIR)
    if f.endswith(".yaml") and f != GLOSSARY_FILENAME
)

for file_name in slot_files:
    slot_path = os.path.join(SLOTS_DIR, file_name)
    with open(slot_path, "r") as f:
        slot_content = yaml.safe_load(f)

        if not slot_content:
            continue

        if "name" in slot_content:
            slot_name = slot_content["name"]
            normalize_slot_def(slot_content)
            schema["slots"][slot_name] = slot_content
            schema["classes"]["MetadataChecklist"]["slots"].append(slot_name)
        else:
            for slot_name, slot_def in slot_content.items():
                normalize_slot_def(slot_def)
                schema["slots"][slot_name] = slot_def
                schema["classes"]["MetadataChecklist"]["slots"].append(slot_name)

# Sort class slot list
schema["classes"]["MetadataChecklist"]["slots"].sort()


# Convert OrderedDicts to regular dicts before dumping
from collections import OrderedDict
import yaml

# Helper function to recursively convert OrderedDict to dict
def convert_ordered_dict(obj):
    if isinstance(obj, OrderedDict):
        return {k: convert_ordered_dict(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_ordered_dict(i) for i in obj]
    else:
        return obj

# Cleaned-up version of schema
clean_schema = convert_ordered_dict(schema)

# Header comment
header_comment = (
    "# ============================\n"
    "# AUTO-GENERATED FILE\n"
    "# This file was automatically rebuilt from individual slot YAML files.\n"
    "# DO NOT EDIT THIS FILE BY HAND.\n"
    "# ============================\n\n"
)

# Write to file (force UTF-8 so non-ASCII characters don't break on Windows)
with open("schema.yaml", "w", encoding="utf-8") as f:
    f.write(header_comment)
    yaml.dump(clean_schema, f, sort_keys=False, allow_unicode=True)

print(f"✅ Merged schema written to {OUTPUT_SCHEMA}")
